# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
from graph import Graph

class Ui_MainWindow(object):
    g = Graph(0)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 680)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_av = QtWidgets.QLabel(self.centralwidget)
        self.label_av.setGeometry(QtCore.QRect(10, 20, 340, 40))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_av.setFont(font)
        self.label_av.setStyleSheet("\n" "")
        self.label_av.setTextFormat(QtCore.Qt.AutoText)
        self.label_av.setAlignment(QtCore.Qt.AlignCenter)
        self.label_av.setObjectName("label_av")
        self.spin_av = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_av.setGeometry(QtCore.QRect(345, 20, 75, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.spin_av.setFont(font)
        self.spin_av.setStyleSheet("")
        self.spin_av.setMinimum(1)
        self.spin_av.setMaximum(9999)
        self.spin_av.setObjectName("spin_av")
        self.btn_ae = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ae.setGeometry(QtCore.QRect(20, 240, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(12)
        self.btn_ae.setFont(font)
        self.btn_ae.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.btn_ae.setObjectName("btn_ae")
        self.spin_ae_sver = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_ae_sver.setGeometry(QtCore.QRect(20, 190, 150, 40))
        self.spin_ae_sver.setMinimum(1)
        self.spin_ae_sver.setObjectName("spin_ae_sver")
        self.label_ae_sver = QtWidgets.QLabel(self.centralwidget)
        self.label_ae_sver.setGeometry(QtCore.QRect(20, 170, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(8)
        self.label_ae_sver.setFont(font)
        self.label_ae_sver.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ae_sver.setObjectName("label_ae_sver")
        self.label_ae_edge = QtWidgets.QLabel(self.centralwidget)
        self.label_ae_edge.setGeometry(QtCore.QRect(320, 170, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Century")
        self.label_ae_edge.setFont(font)
        self.label_ae_edge.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ae_edge.setObjectName("label_ae_edge")
        self.label_ae_fver = QtWidgets.QLabel(self.centralwidget)
        self.label_ae_fver.setGeometry(QtCore.QRect(170, 170, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Century")
        self.label_ae_fver.setFont(font)
        self.label_ae_fver.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ae_fver.setObjectName("label_ae_fver")
        self.spin_ae_fver = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_ae_fver.setGeometry(QtCore.QRect(170, 190, 150, 40))
        self.spin_ae_fver.setMinimum(1)
        self.spin_ae_fver.setObjectName("spin_ae_fver")
        self.spin_ae_edge = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_ae_edge.setGeometry(QtCore.QRect(320, 190, 100, 40))
        self.spin_ae_edge.setMinimum(-1000)
        self.spin_ae_edge.setMaximum(1000)
        self.spin_ae_edge.setObjectName("spin_ae_edge")
        self.label_ae = QtWidgets.QLabel(self.centralwidget)
        self.label_ae.setGeometry(QtCore.QRect(10, 120, 420, 40))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_ae.setFont(font)
        self.label_ae.setStyleSheet("")
        self.label_ae.setTextFormat(QtCore.Qt.AutoText)
        self.label_ae.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ae.setObjectName("label_ae")
        self.label_bal = QtWidgets.QLabel(self.centralwidget)
        self.label_bal.setGeometry(QtCore.QRect(10, 290, 420, 40))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_bal.setFont(font)
        self.label_bal.setStyleSheet("")
        self.label_bal.setTextFormat(QtCore.Qt.AutoText)
        self.label_bal.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bal.setObjectName("label_bal")
        self.spin_bal_sver = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_bal_sver.setGeometry(QtCore.QRect(20, 360, 140, 40))
        self.spin_bal_sver.setMinimum(1)
        self.spin_bal_sver.setObjectName("spin_bal_sver")
        self.label_bal_sver = QtWidgets.QLabel(self.centralwidget)
        self.label_bal_sver.setGeometry(QtCore.QRect(20, 340, 140, 20))
        font = QtGui.QFont()
        font.setFamily("Century")
        self.label_bal_sver.setFont(font)
        self.label_bal_sver.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bal_sver.setObjectName("label_bal_sver")
        self.btn_bal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bal.setGeometry(QtCore.QRect(170, 340, 250, 60))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(12)
        self.btn_bal.setFont(font)
        self.btn_bal.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.btn_bal.setObjectName("btn_bal")
        self.label_result = QtWidgets.QTextBrowser(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(10, 410, 420, 150))
        self.label_result.setObjectName("label_result")
        self.btn_av = QtWidgets.QPushButton(self.centralwidget)
        self.btn_av.setGeometry(QtCore.QRect(20, 70, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(12)
        font.setItalic(False)
        self.btn_av.setFont(font)
        self.btn_av.setStyleSheet("background-color: rgb(255, 170, 127);\n"
                                  "\n"
                              "")
        self.btn_av.setObjectName("btn_av")
        self.btn_clean = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clean.setGeometry(QtCore.QRect(20, 570, 400, 40))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(12)
        self.btn_clean.setFont(font)
        self.btn_clean.setObjectName("btn_clean")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 110, 421, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(420, 10, 20, 610))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 280, 420, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 400, 420, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 610, 420, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(10, 0, 420, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(0, 10, 20, 610))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(10, 550, 420, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_av.raise_()
        self.spin_av.raise_()
        self.btn_ae.raise_()
        self.spin_ae_sver.raise_()
        self.label_ae_sver.raise_()
        self.label_ae_edge.raise_()
        self.label_ae_fver.raise_()
        self.spin_ae_fver.raise_()
        self.spin_ae_edge.raise_()
        self.label_ae.raise_()
        self.label_bal.raise_()
        self.spin_bal_sver.raise_()
        self.label_bal_sver.raise_()
        self.btn_bal.raise_()
        self.label_result.raise_()
        self.btn_clean.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.btn_av.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Форд-Беллман"))
        self.label_av.setText(_translate("MainWindow", "Введите количество вершин"))
        self.btn_ae.setText(_translate("MainWindow", "Добавить ребро"))
        self.label_ae_sver.setText(_translate("MainWindow", "Начальная вершина"))
        self.label_ae_edge.setText(_translate("MainWindow", "Длина ребра"))
        self.label_ae_fver.setText(_translate("MainWindow", "Конечная вершина"))
        self.label_ae.setText(_translate("MainWindow", "Добавление ребра"))
        self.label_bal.setText(_translate("MainWindow", "Кратчайший путь"))
        self.label_bal_sver.setText(_translate("MainWindow", "Начальная вершина"))
        self.btn_bal.setText(_translate("MainWindow", "Посчитать путь"))
        self.btn_av.setText(_translate("MainWindow", "Создать граф"))
        self.btn_clean.setText(_translate("MainWindow", "Очистить граф"))

    def add_functions(self):
        self.btn_av.clicked.connect(lambda: self.write_vert(self.spin_av.value()))
        self.btn_ae.clicked.connect(
            lambda: self.write_edge(self.spin_ae_sver.value(), self.spin_ae_fver.value(), self.spin_ae_edge.value()))
        self.btn_bal.clicked.connect(lambda: self.write_bal(self.spin_bal_sver.value()))
        self.btn_clean.clicked.connect(lambda: self.clean())

    def write_vert(self, value):
        self.g = Graph(value)
        self.label_result.setText("Создан граф, количство вершин: " + str(value))

    def write_edge(self, sver, fver, edge):
        if sver <= self.g.get_v() and fver <= self.g.get_v():
            self.g.addEdge(sver - 1, fver - 1, edge)
            self.label_result.setText(self.label_result.toPlainText() + "\n" + "\n" +
                "Добавлено ребро из вершины " + str(sver) + " в вершину " + str(fver) + " длиной " + str(edge))
        else:
            self.label_result.setText(self.label_result.toPlainText() + "\n" + "\n" +
                "Неверно введена начальная или конечная вершина")


    def write_bal(self, sver):
        if sver <= self.g.get_v():
            self.g.BellmanFord(sver - 1)
            self.label_result.setText(self.label_result.toPlainText() + "\n" + "\n" + self.g.get_s())
        else:
            self.label_result.setText(self.label_result.toPlainText() + "\n" + "\n" +
                "Неверно введена вершина")

    def clean(self):
        self.label_result.setText("")
        self.g = Graph(0)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
